### ISSUE TITLE
Nodejs: Don't use lodash.union if it is unnecessary.

### ISSUE THREAD

**Issue by landrito** [googleapis/packman#144]
### What

When generating the index.js for an api, we are using lodash.union to combine the sets of scopes. This is unneeded for situations where there is no scopes or there is only one service which a non empty set of scopes.
### Example

This can be seen in monitoring where this [line](https://github.com/googleapis/api-client-staging/blob/master/generated/nodejs/google-cloud-node/packages/monitoring/src/v3/index.js#L35) is uneeded since the scopes exported by [group-service-api](https://github.com/googleapis/api-client-staging/blob/master/generated/nodejs/google-cloud-node/packages/monitoring/src/v3/group_service_api.js#L56) and [metric-service-api](https://github.com/googleapis/api-client-staging/blob/master/generated/nodejs/google-cloud-node/packages/monitoring/src/v3/metric_service_api.js#L60) are empty.
### Expected

Packman should be smart enough to see that there is no scopes exported, to simply set `ALL_SCOPES` to `[]`, and to not require lodash.union in index.js or as a dependency.

**Comment by landrito** [comment]
cc @jmuk

**Comment by jmuk** [comment]
Oh, I see. Also some APIs have exactly same set of scopes among services (like pubsub: https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/pubsub/src/v1/publisher_api.js#L56 and https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/pubsub/src/v1/subscriber_api.js#L52). In that case actually `union` isn't necessary.

However, it's hard to do that because packman does not receive gapic config. I think the way is to move the generation of the `index.js` to toolkit (codegen) and add behaviors like that.

**Comment by landrito** [comment]
Agreed. I am filing this issue here until it is moved into toolkit.

**Comment by landrito** [comment]
This seems to be fixed with https://github.com/googleapis/toolkit/pull/867.
